In [5]:
import numpy as np

In [21]:
# 1
np1 = np.arange(1, 16 + 1)
print(np1.reshape(4, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
# 2
np2 = np.arange(10, 50, 5)
print(np2.reshape(2, 4))

[[10 15 20 25]
 [30 35 40 45]]


In [25]:
# 3
np3 = np.random.randint(1, 100, (3, 3))
print(np3)
print('min', np3.min())
print('max', np3.max())

[[44 16 63]
 [84  8 78]
 [22 32 94]]
min 8
max 94


In [31]:
# 4
np4 = np.random.randint(0, 20, 10)
print(np4)
print('1', np4[:5])
print('2', np4[::2])
print('3', np4[::-1])

[16 14  1  6  2  9  4 18  0 14]
1 [16 14  1  6  2]
2 [16  1  2  4  0]
3 [14  0 18  4  9  2  6  1 14 16]


In [37]:
# 5
np5 = np.random.randint(0, 50, (4, 5))
print(np5, '\n')
print(np5[2][4])

[[22 45 45 18 37]
 [ 9 16 48 39 11]
 [40  8 49 15 33]
 [19 16 15 32  2]] 

33


In [23]:
# 6
np6 = np.random.randint(0, 100, 15)
print(np6, '\n')
print('max', np6.argmax())
print('min', np6.argmin())

# 6 continue
np.save('fifteen.npy', np6)

np6 = np.load('fifteen.npy')

print('numbers % 5 == 0', np6[(np6 % 5 == 0)])
print('numbers > 50 or numbers < 10', np6[(np6 > 50) | (np6 < 10)])

[96 13 83 60 13 69 69 19 89 76 22 90 18 66  3] 

max 0
min 14
numbers % 5 == 0 [60 90]
numbers > 50 or numbers < 10 [96 83 60 69 69 89 76 90 66  3]
